import { useLanguage } from "../context/LanguageContext.jsx";

const classes = {
  BORRADOR: "badge badge-gray",
  EN_VALIDACION: "badge badge-blue",
  ENVIADO: "badge badge-blue",
  PENDIENTE_APROBACION: "badge badge-amber",
  OBSERVADO: "badge badge-red",
  DEVUELTO: "badge badge-amber",
  APROBADO_DIRECTOR: "badge badge-blue",
  APROBADO_VICERRECTOR: "badge badge-blue",
  COMPROMISO_PRESUPUESTAL: "badge badge-amber",
  CONTABILIZADO: "badge badge-blue",
  PROGRAMADO: "badge badge-blue",
  RECHAZADO: "badge badge-red",
  TXT_GENERADO: "badge badge-indigo",
  PAGADO: "badge badge-green",
  CONCILIADO: "badge badge-green",
  RENDICION_PENDIENTE: "badge badge-amber",
  CERRADO: "badge badge-dark",
  ANULADO: "badge badge-red",
  PENDING_VALIDATION: "badge badge-amber",
  OBSERVED: "badge badge-red",
  TRANSITIONAL: "badge badge-gray",
  ACTIVE: "badge badge-green",
  RESERVED: "badge badge-amber",
  COMMITTED: "badge badge-amber",
  NO_BUDGET: "badge badge-gray",
  AVAILABLE: "badge badge-green",
  CLOSED_BUDGET: "badge badge-dark",
  WITHOUT_BUDGET: "badge badge-gray",
  EXECUTED: "badge badge-green",
  PAID: "badge badge-green",
  RELEASED: "badge badge-blue",
  HOMOLOGATED: "badge badge-green",
  COMPLIANT: "badge badge-green",
  NON_COMPLIANT: "badge badge-red",
  SCHEDULED: "badge badge-blue",
  PAYMENT_FILE_CREATED: "badge badge-indigo",
  CANCELLED: "badge badge-red",
  VALIDATED: "badge badge-green",
  PENDING: "badge badge-amber",
  APPROVED: "badge badge-green",
  REJECTED: "badge badge-red",
  BLOCKED: "badge badge-red",
  COMPLETED: "badge badge-green",
  GENERATED: "badge badge-indigo",
  PARTIALLY_CONFIRMED: "badge badge-amber",
  CONFIRMED: "badge badge-green",
  NOT_REQUIRED: "badge badge-gray",
  SUBMITTED: "badge badge-blue",
  DEMO: "badge badge-amber"
};

export default function StatusBadge({ status }) {
  const { t } = useLanguage();
  return <span className={classes[status] || "badge badge-gray"}>{t(status || "N/A")}</span>;
}
