import { createContext, useContext, useEffect, useMemo, useState } from "react";

const spanish = {
  "ERP Financial Control": "Control Financiero ERP",
  "Financial Control": "Control Financiero",
  "Requests & payments": "Solicitudes y pagos",
  Dashboard: "Panel",
  Requests: "Solicitudes",
  "Approval Inbox": "Bandeja de aprobaciones",
  Accounting: "Contabilidad",
  Treasury: "Tesorería",
  Suppliers: "Proveedores",
  "Cost Centers": "Centros de costos",
  "Expense Types": "Tipos de gasto",
  "Exchange Rates": "Tipos de cambio",
  Periods: "Periodos",
  "SIRE Export": "Exportación SIRE",
  "Admin Users": "Usuarios admin",
  "Log out": "Salir",
  Language: "Idioma",
  English: "Inglés",
  Spanish: "Español",
  EN: "EN",
  ES: "ES",
  "Loading session...": "Cargando sesión...",
  "No records found": "No se encontraron registros",
  "Adjust filters or create a new record.": "Ajusta los filtros o crea un nuevo registro.",
  "No workflow events yet.": "Aún no hay eventos de flujo.",
  START: "INICIO",
  System: "Sistema",
  Edit: "Editar",
  "Delete or deactivate": "Eliminar o desactivar",
  "Record updated.": "Registro actualizado.",
  "Record created.": "Registro creado.",
  "Record removed or deactivated.": "Registro eliminado o desactivado.",
  "Edit record": "Editar registro",
  "New record": "Nuevo registro",
  Select: "Seleccionar",
  Update: "Actualizar",
  Create: "Crear",
  Cancel: "Cancelar",
  "Loading records...": "Cargando registros...",
  "File download failed.": "No se pudo descargar el archivo.",
  "No homologation documents uploaded.": "No se cargaron documentos de homologación.",
  "Sign in": "Iniciar sesión",
  "Request intake, document validation, approval, accounting provision, and Treasury payment file generation in one local system.":
    "Registro de solicitudes, validación documental, aprobación, provisión contable y generación de archivos de pago bancario en un sistema local.",
  Email: "Correo",
  Password: "Contraseña",
  "Signing in...": "Ingresando...",
  Login: "Ingresar",
  Admin: "Admin",
  Solicitor: "Solicitante",
  Approver: "Aprobador",
  "Operational snapshot for requests, approvals, payment readiness, and closed work.":
    "Resumen operativo de solicitudes, aprobaciones, pagos listos y procesos cerrados.",
  "Loading dashboard...": "Cargando panel...",
  "Total requests": "Solicitudes totales",
  "Pending approval": "Pendientes de aprobación",
  "Approved / payable": "Aprobadas / por pagar",
  Rejected: "Rechazadas",
  "Processed by bank": "Procesadas por banco",
  "Closed requests": "Solicitudes cerradas",
  "Requests by status": "Solicitudes por estado",
  "Requests by type": "Solicitudes por tipo",
  "Total amount by currency": "Monto total por moneda",
  Status: "Estado",
  Count: "Cantidad",
  Type: "Tipo",
  Currency: "Moneda",
  "Original total": "Total original",
  "PEN equivalent": "Equivalente PEN",
  "Create, track, submit, and review financial requests by status and accounting period.":
    "Crea, controla, envía y revisa solicitudes financieras por estado y período contable.",
  "New request": "Nueva solicitud",
  "All statuses": "Todos los estados",
  "All types": "Todos los tipos",
  "Period 2026-07": "Periodo 2026-07",
  "Apply filters": "Aplicar filtros",
  "Loading requests...": "Cargando solicitudes...",
  Request: "Solicitud",
  Supplier: "Proveedor",
  Period: "Periodo",
  Amount: "Monto",
  "Create request": "Crear solicitud",
  "Mandatory accounting dimensions are enforced on every line before saving.":
    "Las dimensiones contables obligatorias se validan en cada línea antes de guardar.",
  "Request type": "Tipo de solicitud",
  "Issue date": "Fecha de emisión",
  "Accounting period": "Periodo contable",
  Description: "Descripción",
  "Request lines": "Líneas de solicitud",
  "Cost center": "Centro de costos",
  "Expense type / account": "Tipo de gasto / cuenta",
  Net: "Neto",
  IGV: "IGV",
  Total: "Total",
  "Remove line": "Quitar línea",
  "Add line": "Agregar línea",
  Quotation: "Cotización",
  "Supporting documents": "Sustentos",
  "Net amount": "Monto neto",
  "IGV amount": "Monto IGV",
  "Total amount": "Monto total",
  "Save draft": "Guardar borrador",
  "Submit for approval": "Enviar a aprobación",
  "Request submitted for approval.": "Solicitud enviada a aprobación.",
  "Request approved.": "Solicitud aprobada.",
  "Request rejected.": "Solicitud rechazada.",
  "Request closed.": "Solicitud cerrada.",
  "Rendition submitted and request closed.": "Rendición enviada y solicitud cerrada.",
  "Loading request...": "Cargando solicitud...",
  "Back to list": "Volver a la lista",
  "Expense account": "Cuenta de gasto",
  Attachments: "Adjuntos",
  Kind: "Tipo",
  File: "Archivo",
  Open: "Abrir",
  "XML validated against supplier and request amounts.": "XML validado contra el proveedor y los montos de la solicitud.",
  "Approval decision": "Decisión de aprobación",
  Approve: "Aprobar",
  "Rejection comments": "Comentarios de rechazo",
  Reject: "Rechazar",
  "Close request": "Cerrar solicitud",
  "Closing comments": "Comentarios de cierre",
  "Receipts/support": "Comprobantes/sustentos",
  Comments: "Comentarios",
  "Submit rendition": "Enviar rendición",
  "Approval timeline": "Línea de aprobación",
  "Review pending requests and move them to payable or rejected status.":
    "Revisa solicitudes pendientes y muévelas a por pagar o rechazadas.",
  "Request approved and provision entry generated.": "Solicitud aprobada y asiento de provisión generado.",
  "Approved from inbox.": "Aprobado desde la bandeja.",
  Decision: "Decisión",
  "Accounting Entries": "Asientos contables",
  "Provision, payment, and rendition entries generated by request workflow events.":
    "Asientos de provisión, pago y rendición generados por eventos del flujo.",
  "Consolidated preview generated.": "Vista consolidada generada.",
  "Load entries": "Cargar asientos",
  Consolidate: "Consolidar",
  "Export CSV": "Exportar CSV",
  "Accounting entries": "Asientos contables",
  Entry: "Asiento",
  Account: "Cuenta",
  Debit: "Debe",
  Credit: "Haber",
  "Month-end consolidation preview": "Vista de consolidación mensual",
  CeCo: "CeCo",
  "Accounting Periods": "Periodos contables",
  "Closed periods block creation, edits, approvals, payments, and closing changes.":
    "Los períodos cerrados bloquean creación, edición, aprobación, pagos y cierres.",
  "Closing date": "Fecha de cierre",
  "Closed by": "Cerrado por",
  "Manage seeded and manually created users, roles, and active status.":
    "Gestiona usuarios iniciales y manuales, roles y estado activo.",
  Name: "Nombre",
  Role: "Rol",
  Area: "Área",
  Active: "Activo",
  Inactive: "Inactivo",
  "Phase 1 tracks assigned, executed, and available budgets without blocking requests.":
    "La fase 1 controla presupuesto asignado, ejecutado y disponible sin bloquear solicitudes.",
  Code: "Código",
  "Annual assigned budget": "Presupuesto anual asignado",
  "Executed amount": "Monto ejecutado",
  Budget: "Presupuesto",
  Executed: "Ejecutado",
  Available: "Disponible",
  Yes: "Sí",
  No: "No",
  "Manual daily SUNAT selling exchange rates used to convert USD requests to PEN.":
    "Tipos de cambio venta SUNAT diarios registrados manualmente para convertir solicitudes USD a PEN.",
  "Daily SBS selling exchange rates used to convert USD requests to PEN. Load the latest published value online or enter one manually.":
    "Tipos de cambio venta SBS diarios usados para convertir solicitudes USD a PEN. Carga el último valor publicado en línea o ingresa uno manualmente.",
  Date: "Fecha",
  "Selling rate": "Tipo de cambio venta",
  Source: "Fuente",
  Rate: "Tipo de cambio",
  "Expense Type": "Tipo de gasto",
  "Accounting account catalog for OPEX, CAPEX, and non-deductible request lines.":
    "Catálogo de cuentas contables para líneas OPEX, CAPEX y no deducibles.",
  Category: "Categoría",
  "Accounting class": "Clase contable",
  "Account number": "Número de cuenta",
  Class: "Clase",
  "Maintain unique RUC/DNI records and bank details used by Treasury payment files.":
    "Mantén RUC/DNI únicos y datos bancarios usados por los archivos de pago de Tesorería.",
  "RUC/DNI": "RUC/DNI",
  "Supplier name": "Nombre del proveedor",
  "Bank name": "Banco",
  "Bank account": "Cuenta bancaria",
  Bank: "Banco",
  "Treasury Payment Queue": "Cola de pagos de Tesorería",
  "Select approved requests and generate a bank TXT for mass payment.":
    "Selecciona solicitudes aprobadas y genera un TXT bancario para pago masivo.",
  Refresh: "Actualizar",
  "Generate bank TXT": "Generar TXT bancario",
  "Download generated TXT": "Descargar TXT generado",
  "Bank / CCI": "Banco / CCI",
  "SIRE RCE Export": "Exportación SIRE RCE",
  "Export approved and XML-validated purchases for Registro de Compras Electrónico review.":
    "Exporta compras aprobadas y validadas con XML para revisión del Registro de Compras Electrónico.",
  Preview: "Vista previa",
  "Supplier RUC": "RUC proveedor",
  Invoice: "Factura",
  OPEX: "OPEX",
  CAPEX: "CAPEX",
  "Entrega a Rendir": "Entrega a Rendir",
  "Reembolso con Sustento": "Reembolso con Sustento",
  "Reembolso sin Sustento": "Reembolso sin Sustento",
  "Pago con Cotización": "Pago con Cotización",
  "Non-deductible": "No deducible",
  "Class 6": "Clase 6",
  "Class 3": "Clase 3",
  "Account 99": "Cuenta 99",
  "Manual SUNAT selling rate": "Tipo de cambio venta SUNAT manual",
  "Get latest online rate": "Obtener último tipo de cambio en línea",
  "Getting online rate...": "Obteniendo tipo de cambio...",
  "Load the latest published BCRP/SBS selling rate into an editable form.": "Carga el último tipo de cambio venta BCRP/SBS publicado en un formulario editable.",
  "You can edit the online value before saving.": "Puedes editar el valor en línea antes de guardar.",
  "Keep the online source or describe the approved manual source.": "Conserva la fuente en línea o describe la fuente manual aprobada.",
  "Enter a rate greater than zero.": "Ingresa un tipo de cambio mayor que cero.",
  ACTIVE: "ACTIVO",
  INACTIVE: "INACTIVO",
  OPEN: "ABIERTO",
  CLOSED: "CERRADO",
  BORRADOR: "BORRADOR",
  EN_VALIDACION: "EN VALIDACIÓN",
  PENDIENTE_APROBACION: "PENDIENTE APROBACIÓN",
  RECHAZADO: "RECHAZADO",
  APROBADO_POR_PAGAR: "APROBADO POR PAGAR",
  PROCESADO_BANCO: "PROCESADO BANCO",
  RENDICION_PENDIENTE: "RENDICIÓN PENDIENTE",
  LIQUIDADO_CERRADO: "LIQUIDADO CERRADO",
  CREATED: "CREADO",
  SUBMITTED: "ENVIADO",
  APPROVED: "APROBADO",
  REJECTED: "RECHAZADO",
  CLOSED_ACTION: "CERRADO",
  BANK_FILE_GENERATED: "ARCHIVO BANCARIO GENERADO",
  RENDITION_SUBMITTED: "RENDICIÓN ENVIADA"
};

const additionalSpanish = {
  Overview: "Resumen",
  Operations: "Operaciones",
  Finance: "Finanzas",
  "Master Data": "Datos maestros",
  Administration: "Administración",
  Users: "Usuarios",
  "Accounting Entries": "Asientos contables",
  "Accounting Periods": "Periodos contables",
  "Primary navigation": "Navegación principal",
  "Open navigation": "Abrir navegación",
  "Close navigation": "Cerrar navegación",
  "Expand sidebar": "Expandir barra lateral",
  "Collapse sidebar": "Contraer barra lateral",
  Breadcrumbs: "Ruta de navegación",
  "Open task notifications": "Abrir notificaciones de tareas",
  "Tasks and alerts": "Tareas y alertas",
  "No pending tasks.": "No hay tareas pendientes.",
  Notifications: "Notificaciones",
  "Dismiss notification": "Descartar notificación",
  "Close dialog": "Cerrar diálogo",
  "Close panel": "Cerrar panel",
  "{count} pending tasks": "{count} tareas pendientes",
  Confirm: "Confirmar",
  "Processing...": "Procesando...",
  "Add comments": "Agregar comentarios",
  "A comment is required to continue.": "Se requiere un comentario para continuar.",
  "Search records...": "Buscar registros...",
  Search: "Buscar",
  "Clear filters": "Limpiar filtros",
  "Showing {shown} of {total} results": "Mostrando {shown} de {total} resultados",
  "{count} selected": "{count} seleccionados",
  "Rows per page": "Filas por página",
  "Page {page} of {pages}": "Página {page} de {pages}",
  "Previous page": "Página anterior",
  "Next page": "Página siguiente",
  "Select all visible rows": "Seleccionar todas las filas visibles",
  "Select row": "Seleccionar fila",
  "Row actions": "Acciones de fila",
  "Close actions": "Cerrar acciones",
  Actions: "Acciones",
  "No records match the current filters.": "Ningún registro coincide con los filtros actuales.",
  "Search options...": "Buscar opciones...",
  "No matching options": "No hay opciones coincidentes",
  "Clear selection": "Limpiar selección",
  "View details": "Ver detalles",
  "Record details": "Detalle del registro",
  Deactivate: "Desactivar",
  "Delete permanently": "Eliminar permanentemente",
  "Deactivate record?": "¿Desactivar el registro?",
  "Permanently delete record?": "¿Eliminar permanentemente el registro?",
  "The record will remain in history but cannot be used for new operations.": "El registro permanecerá en el historial, pero no podrá usarse en nuevas operaciones.",
  "This record will be permanently removed and cannot be restored.": "Este registro se eliminará permanentemente y no podrá restaurarse.",
  "Record deactivated.": "Registro desactivado.",
  "Record permanently deleted.": "Registro eliminado permanentemente.",
  "This field is required.": "Este campo es obligatorio.",
  "This value already exists.": "Este valor ya existe.",
  "Saving...": "Guardando...",
  "Required when creating a user.": "Obligatorio al crear un usuario.",
  "Supplier bank history": "Historial bancario del proveedor",
  "Close accounting period?": "¿Cerrar el período contable?",
  "Reopen accounting period?": "¿Reabrir el período contable?",
  "Closing the period will block request creation, edits, approvals, payments, renditions, and closures for this period.": "Cerrar el período bloqueará la creación, edición, aprobación, pagos, rendiciones y cierres de este período.",
  "Reopening the period will allow workflow and accounting changes again.": "Reabrir el período permitirá nuevamente cambios de flujo y contabilidad.",
  "Close period": "Cerrar período",
  "Reopen period": "Reabrir período",
  Result: "Resultado",
  "Status changes to CLOSED": "El estado cambia a CERRADO",
  "Status changes to OPEN": "El estado cambia a ABIERTO",
  "Admin Dashboard": "Panel de administración",
  "Solicitor Dashboard": "Panel del solicitante",
  "Approver Dashboard": "Panel del aprobador",
  "Accounting Dashboard": "Panel de contabilidad",
  "Treasury Dashboard": "Panel de tesorería",
  "System activity, workflow health, users, and master-data readiness.": "Actividad del sistema, salud del flujo, usuarios y preparación de datos maestros.",
  "Your drafts, approvals, rejected work, renditions, and recent requests.": "Tus borradores, aprobaciones, rechazos, rendiciones y solicitudes recientes.",
  "Approval workload, waiting value, oldest requests, and recent decisions.": "Carga de aprobación, monto en espera, solicitudes más antiguas y decisiones recientes.",
  "Period readiness, accounting entries, exchange rates, and pending closures.": "Preparación del período, asientos, tipos de cambio y cierres pendientes.",
  "Payable workload, currency totals, bank readiness, and generated files.": "Carga por pagar, totales por moneda, preparación bancaria y archivos generados.",
  "My drafts": "Mis borradores",
  "Rejected requests": "Solicitudes rechazadas",
  "Rendition tasks": "Tareas de rendición",
  "Completed requests": "Solicitudes completadas",
  "Active users": "Usuarios activos",
  "PEN equivalent waiting": "Equivalente PEN en espera",
  "Oldest request age": "Antigüedad de la solicitud más antigua",
  days: "días",
  "Current period": "Periodo actual",
  "Entries this period": "Asientos del período",
  "Debit total": "Total debe",
  "Credit total": "Total haber",
  "Pending closures": "Cierres pendientes",
  "Payable queue": "Cola por pagar",
  "PEN waiting": "PEN en espera",
  "USD waiting": "USD en espera",
  "Missing bank details": "Datos bancarios faltantes",
  "Recent bank files": "Archivos bancarios recientes",
  "Items need attention": "Hay elementos que requieren atención",
  "Recent requests": "Solicitudes recientes",
  "Oldest requests awaiting decision": "Solicitudes más antiguas pendientes de decisión",
  "Next payable requests": "Próximas solicitudes por pagar",
  "Current operational work in priority order.": "Trabajo operativo actual en orden de prioridad.",
  "View all": "Ver todo",
  "Workflow distribution": "Distribución del flujo",
  "Requests grouped by current status.": "Solicitudes agrupadas por estado actual.",
  "No request data available.": "No hay datos de solicitudes disponibles.",
  "Recent decisions": "Decisiones recientes",
  "Requests you recently approved or rejected.": "Solicitudes que aprobaste o rechazaste recientemente.",
  "Recent accounting periods": "Periodos contables recientes",
  "Open and closed period status.": "Estado de períodos abiertos y cerrados.",
  "Manage periods": "Gestionar períodos",
  "Recent generated files": "Archivos generados recientemente",
  "Bank and accounting exports created by the team.": "Exportaciones bancarias y contables creadas por el equipo.",
  Rows: "Filas",
  Generated: "Generado",
  "Generated by": "Generado por",
  "No current requests.": "No hay solicitudes actuales.",
  "Request quick view": "Vista rápida de solicitud",
  "Edit request": "Editar solicitud",
  "Open full details": "Abrir detalle completo",
  "Accounting lines": "Líneas contables",
  "Latest activity": "Actividad reciente",
  "Quick view": "Vista rápida",
  Solicitor: "Solicitante",
  Updated: "Actualizado",
  "Search request, supplier, solicitor...": "Buscar solicitud, proveedor o solicitante...",
  "Search request, supplier, or solicitor...": "Buscar solicitud, proveedor o solicitante...",
  "All periods": "Todos los períodos",
  "All currencies": "Todas las monedas",
  "All entry types": "Todos los tipos de asiento",
  "Permanently delete this request?": "¿Eliminar permanentemente esta solicitud?",
  "Only draft or rejected requests can be deleted. This action cannot be undone.": "Solo se pueden eliminar solicitudes en borrador o rechazadas. Esta acción no se puede deshacer.",
  "The request and its draft data will be permanently removed.": "La solicitud y sus datos de borrador se eliminarán permanentemente.",
  "Draft request permanently deleted.": "Solicitud en borrador eliminada permanentemente.",
  "Basic information": "Información básica",
  Documents: "Documentos",
  "Review and submit": "Revisar y enviar",
  "Request progress": "Progreso de la solicitud",
  "Complete each step. Your form data is saved locally while you work.": "Completa cada paso. Los datos del formulario se guardan localmente mientras trabajas.",
  "Loading form data...": "Cargando datos del formulario...",
  "Recovered local draft": "Borrador local recuperado",
  "Saving locally...": "Guardando localmente...",
  "Saved locally": "Guardado localmente",
  "Autosave ready": "Autoguardado listo",
  "Identify the supplier, request type, period, and purpose.": "Identifica el proveedor, tipo de solicitud, período y propósito.",
  "Use YYYY-MM format.": "Usa el formato AAAA-MM.",
  "Closed periods cannot be used.": "No se pueden usar períodos cerrados.",
  "A SUNAT selling rate is required for this date or period.": "Se requiere un tipo de cambio venta SUNAT para esta fecha o período.",
  "Exchange rate is fixed at 1.00.": "El tipo de cambio está fijado en 1.00.",
  "Search by supplier name or RUC/DNI...": "Buscar por nombre del proveedor o RUC/DNI...",
  "This supplier has no bank account or CCI. Treasury will not be able to generate payment.": "Este proveedor no tiene cuenta bancaria ni CCI. Tesorería no podrá generar el pago.",
  "Describe the business purpose and what is being paid.": "Describe el propósito del negocio y qué se está pagando.",
  "Assign every amount to a cost center and expense account.": "Asigna cada monto a un centro de costos y una cuenta de gasto.",
  "Select a cost center.": "Selecciona un centro de costos.",
  "Select an expense account.": "Selecciona una cuenta de gasto.",
  "Enter a valid net amount.": "Ingresa un monto neto válido.",
  "Enter a valid IGV amount.": "Ingresa un monto de IGV válido.",
  "Total must be greater than zero.": "El total debe ser mayor que cero.",
  "Search cost center...": "Buscar centro de costos...",
  "Search expense account...": "Buscar cuenta de gasto...",
  "At least one line is required.": "Se requiere al menos una línea.",
  "Net + IGV differs from Total by {amount}.": "Neto + IGV difiere del total en {amount}.",
  "Combined Net + IGV does not equal Total.": "La suma de Neto + IGV no coincide con el total.",
  "XML and PDF are required for this request type before submission.": "Se requieren XML y PDF para este tipo de solicitud antes del envío.",
  "Attach the documents needed to support this request.": "Adjunta los documentos necesarios para sustentar esta solicitud.",
  "Mandatory invoice validation": "Validación obligatoria de factura",
  "Supporting documentation": "Documentación de sustento",
  "The XML supplier RUC/DNI and amounts will be checked against this request. The PDF is also required.": "El RUC/DNI y los montos del XML se validarán contra esta solicitud. También se requiere el PDF.",
  "XML and PDF are optional for this request type. Add quotations or other support when applicable.": "El XML y PDF son opcionales para este tipo. Agrega cotizaciones u otros sustentos cuando corresponda.",
  "Invoice XML": "XML de factura",
  "Invoice PDF": "PDF de factura",
  Quotations: "Cotizaciones",
  "Choose file": "Elegir archivo",
  "Already uploaded": "Ya cargado",
  "XML is required for this request type.": "El XML es obligatorio para este tipo de solicitud.",
  "PDF is required for this request type.": "El PDF es obligatorio para este tipo de solicitud.",
  "Confirm the request details before sending it into the approval workflow.": "Confirma los detalles antes de enviar la solicitud al flujo de aprobación.",
  "No files attached.": "No hay archivos adjuntos.",
  "Net + IGV does not equal Total. You may save a draft, but verify amounts before submission.": "Neto + IGV no coincide con el total. Puedes guardar un borrador, pero verifica los montos antes de enviar.",
  Back: "Atrás",
  Continue: "Continuar",
  "Submitting...": "Enviando...",
  "Review the highlighted fields before continuing.": "Revisa los campos resaltados antes de continuar.",
  "Draft request updated.": "Solicitud en borrador actualizada.",
  "Draft request created.": "Solicitud en borrador creada.",
  "Request details": "Detalle de solicitud",
  "Request workflow status": "Estado del flujo de la solicitud",
  "Requested by": "Solicitado por",
  "Request summary": "Resumen de solicitud",
  "Exchange rate": "Tipo de cambio",
  "Cost centers, expense accounts, and validated request amounts.": "Centros de costos, cuentas de gasto y montos validados de la solicitud.",
  "Supporting files and invoice validation documents.": "Archivos de sustento y documentos de validación de factura.",
  Size: "Tamaño",
  Uploaded: "Cargado",
  "Preview or download": "Vista previa o descarga",
  "XML validation passed": "Validación XML aprobada",
  "No validated XML": "No hay XML validado",
  "Supplier RUC/DNI and invoice amounts match this request.": "El RUC/DNI del proveedor y los montos de la factura coinciden con la solicitud.",
  "XML validation is only required for applicable request types.": "La validación XML solo se requiere para los tipos aplicables.",
  "Payment and rendition information": "Información de pago y rendición",
  "Bank file": "Archivo bancario",
  "Rendition submitted": "Rendición enviada",
  "Submitted by": "Enviado por",
  "Available actions": "Acciones disponibles",
  "Actions allowed for your role and this status.": "Acciones permitidas para tu rol y este estado.",
  "Required documents are missing: {documents}.": "Faltan documentos obligatorios: {documents}.",
  "Moves this request to the approval inbox.": "Mueve esta solicitud a la bandeja de aprobación.",
  Submit: "Enviar",
  "Upload the required XML and PDF before submission.": "Carga el XML y PDF obligatorios antes de enviar.",
  "Approve this request?": "¿Aprobar esta solicitud?",
  "Approval will move the request to the Treasury payable queue and create provision accounting entries.": "La aprobación moverá la solicitud a la cola de Tesorería y creará asientos de provisión.",
  "Approve request": "Aprobar solicitud",
  "Reject this request?": "¿Rechazar esta solicitud?",
  "The request will return to the solicitor for correction. A rejection comment is required.": "La solicitud volverá al solicitante para corrección. Se requiere un comentario de rechazo.",
  "Reject request": "Rechazar solicitud",
  "Closing completes the request workflow. The accounting period must still be open.": "El cierre completa el flujo. El período contable debe permanecer abierto.",
  "Rendition documents": "Documentos de rendición",
  "{count} files selected": "{count} archivos seleccionados",
  "Receipts and supporting documents are required.": "Se requieren comprobantes y documentos de sustento.",
  "Select at least one rendition document.": "Selecciona al menos un documento de rendición.",
  "Approval and audit timeline": "Línea de aprobación y auditoría",
  "Every workflow decision recorded for this request.": "Cada decisión del flujo registrada para esta solicitud.",
  "Request approved and provision entries generated.": "Solicitud aprobada y asientos de provisión generados.",
  "Request rejected and returned to the solicitor.": "Solicitud rechazada y devuelta al solicitante.",
  "Request closed. Its status is now LIQUIDADO_CERRADO.": "Solicitud cerrada. Su estado ahora es LIQUIDADO_CERRADO.",
  "Rendition submitted, accounting entries generated, and request closed.": "Rendición enviada, asientos generados y solicitud cerrada.",
  "Review pending requests in oldest-first order and record a clear approval decision.": "Revisa solicitudes pendientes desde la más antigua y registra una decisión clara.",
  "Approval comments": "Comentarios de aprobación",
  "Waiting since": "En espera desde",
  "Treasury Payment Queue": "Cola de pagos de Tesorería",
  "Review bank readiness, select payable requests, and generate controlled bank payment files.": "Revisa la preparación bancaria, selecciona solicitudes y genera archivos de pago controlados.",
  "Some payments are blocked": "Algunos pagos están bloqueados",
  "Requests without a supplier bank account or CCI cannot be selected or included in a bank file.": "Las solicitudes sin cuenta bancaria o CCI no se pueden seleccionar ni incluir en un archivo bancario.",
  "{count} requests selected": "{count} solicitudes seleccionadas",
  "Review bank file": "Revisar archivo bancario",
  "Bank file generated successfully": "Archivo bancario generado correctamente",
  "requests processed": "solicitudes procesadas",
  "Download TXT": "Descargar TXT",
  "Payable requests": "Solicitudes por pagar",
  "Only rows with valid bank details can be selected.": "Solo se pueden seleccionar filas con datos bancarios válidos.",
  Approved: "Aprobado",
  "Generated bank-file history": "Historial de archivos bancarios generados",
  "Download previous files and review who generated them.": "Descarga archivos anteriores y revisa quién los generó.",
  "Included requests": "Solicitudes incluidas",
  Totals: "Totales",
  Download: "Descargar",
  "Generate this bank TXT?": "¿Generar este TXT bancario?",
  "Generation is final for these requests: statuses will change and payment accounting entries will be created.": "La generación es final para estas solicitudes: los estados cambiarán y se crearán asientos de pago.",
  "Selected requests": "Solicitudes seleccionadas",
  "Bank TXT generated. Request statuses changed and payment entries were created.": "TXT bancario generado. Los estados cambiaron y se crearon asientos de pago.",
  "Review workflow-generated entries, reconcile totals, consolidate the period, and retain export history.": "Revisa asientos del flujo, concilia totales, consolida el período y conserva el historial de exportación.",
  "Load period": "Cargar período",
  "Exporting...": "Exportando...",
  "Export consolidation CSV": "Exportar CSV de consolidación",
  Entries: "Asientos",
  "Consolidated PEN": "PEN consolidado",
  "Provision, payment, and rendition entries created by the workflow.": "Asientos de provisión, pago y rendición creados por el flujo.",
  "Entry type": "Tipo de asiento",
  Created: "Creado",
  "Consolidation summary": "Resumen de consolidación",
  "Period totals grouped by cost center, expense account, and currency.": "Totales del período agrupados por centro de costos, cuenta de gasto y moneda.",
  "Export history": "Historial de exportación",
  "Previously generated consolidation reports remain available for download.": "Los reportes de consolidación generados permanecen disponibles para descarga.",
  "Consolidation CSV generated and added to export history.": "CSV de consolidación generado y agregado al historial.",
  PROVISION: "PROVISIÓN",
  PAYMENT: "PAGO",
  RENDITION: "RENDICIÓN",
  "Validate XML-backed purchase rows before generating the electronic purchase-register report.": "Valida las compras respaldadas por XML antes de generar el registro electrónico.",
  "Loading preview...": "Cargando vista previa...",
  "Validate preview": "Validar vista previa",
  "Export SIRE CSV": "Exportar CSV SIRE",
  "Eligible purchases": "Compras elegibles",
  "Validation warnings": "Advertencias de validación",
  "Purchase total": "Total de compras",
  "Resolve validation warnings before filing": "Resuelve las advertencias antes de presentar",
  "SIRE preview": "Vista previa SIRE",
  "Only approved requests with a successfully validated XML are included.": "Solo se incluyen solicitudes aprobadas con XML validado correctamente.",
  "Previously generated SIRE reports remain available for download.": "Los reportes SIRE generados permanecen disponibles para descarga.",
  Warnings: "Advertencias",
  "SIRE CSV generated and added to report history.": "CSV SIRE generado y agregado al historial.",
  "ERP operations": "Operaciones ERP",
  "Financial Request & Payment Control": "Control de Solicitudes Financieras y Pagos",
  "Authorized business users only": "Solo usuarios autorizados",
  "Use your assigned company account.": "Usa tu cuenta corporativa asignada.",
  "Local demo access": "Acceso de demostración local",
  "Choose demo role": "Elegir rol de demostración",
  "Sign in": "Iniciar sesión",
  "Budget Control": "Control presupuestal",
  "Management Reports": "Reportes gerenciales",
  "Expense nature": "Naturaleza del gasto",
  "Requesting area": "Área solicitante",
  "School / department": "Escuela / dirección",
  Project: "Proyecto",
  Priority: "Prioridad",
  "Optional project code or name": "Código o nombre de proyecto opcional",
  "Assigned from the signed-in user profile.": "Asignado desde el perfil del usuario conectado.",
  "Compra de Bienes": "Compra de bienes",
  "Contratación de Servicios": "Contratación de servicios",
  "Honorarios Profesionales": "Honorarios profesionales",
  Publicidad: "Publicidad",
  Viajes: "Viajes",
  Equipamiento: "Equipamiento",
  Tecnología: "Tecnología",
  Infraestructura: "Infraestructura",
  Laboratorios: "Laboratorios",
  Biblioteca: "Biblioteca",
  Investigación: "Investigación",
  Mantenimiento: "Mantenimiento",
  "Caja Chica": "Caja chica",
  "Reembolso / Liquidación": "Reembolso / liquidación",
  BAJA: "BAJA",
  MEDIA: "MEDIA",
  ALTA: "ALTA",
  AREA_DIRECTOR: "DIRECTOR DE ÁREA",
  VICE_RECTOR: "VICERRECTOR",
  COMPLETE: "COMPLETADO",
  APROBADO_DIRECTOR: "APROBADO DIRECTOR",
  APROBADO_VICERRECTOR: "APROBADO VICERRECTOR",
  COMPROMISO_PRESUPUESTAL: "COMPROMISO PRESUPUESTAL",
  CONTABILIZADO: "CONTABILIZADO",
  PROGRAMADO: "PROGRAMADO",
  TXT_GENERADO: "TXT GENERADO",
  PAGADO: "PAGADO",
  CONCILIADO: "CONCILIADO",
  ANULADO: "ANULADO",
  PENDING_VALIDATION: "PENDIENTE DE VALIDACIÓN",
  OBSERVED: "OBSERVADO",
  TRANSITIONAL: "TRANSITORIO",
  RESERVED: "RESERVADO",
  WITHOUT_BUDGET: "SIN PRESUPUESTO",
  RELEASED: "LIBERADO",
  "Invoice / receipt PDF": "Factura / comprobante PDF",
  "Purchase order": "Orden de compra",
  "Signed contract": "Contrato firmado",
  "Conformity report": "Informe de conformidad",
  "Activity report": "Informe de actividades",
  "Required documents are determined by the request type and expense nature.": "Los documentos obligatorios se determinan según el tipo de solicitud y la naturaleza del gasto.",
  "Mandatory document checklist": "Lista de documentos obligatorios",
  "Add quotations or other support when applicable.": "Agrega cotizaciones u otros sustentos cuando corresponda.",
  "Upload all required documents before submission.": "Carga todos los documentos obligatorios antes de enviar.",
  "Approval level": "Nivel de aprobación",
  "SLA due": "Vencimiento SLA",
  Overdue: "Vencido",
  "On time": "A tiempo",
  "Director approval recorded and sent to Vice Rector.": "Aprobación del director registrada y enviada al Vicerrector.",
  "Vice Rector approval recorded and budget commitment created.": "Aprobación del Vicerrector registrada y compromiso presupuestal creado.",
  "Assigned budget": "Presupuesto asignado",
  "Committed budget": "Presupuesto comprometido",
  "Executed budget": "Presupuesto ejecutado",
  "Paid budget": "Presupuesto pagado",
  "Available balance": "Saldo disponible",
  "Commitment period": "Periodo del compromiso",
  Apply: "Aplicar",
  "Low budget availability": "Baja disponibilidad presupuestal",
  "One or more active cost centers have less than 10% available.": "Uno o más centros de costo activos tienen menos del 10% disponible.",
  "Budget by cost center": "Presupuesto por centro de costo",
  "Active budgets reserve funds before Accounting registers the payable.": "Los presupuestos activos reservan fondos antes de que Contabilidad registre la cuenta por pagar.",
  "Budget commitments": "Compromisos presupuestales",
  "Every reservation remains traceable to its originating request.": "Cada reserva mantiene trazabilidad con su solicitud de origen.",
  "Committed amount": "Monto comprometido",
  "Budget status": "Estado presupuestal",
  "Budget mode": "Modo presupuestal",
  "All modes": "Todos los modos",
  "CAPEX and OPEX": "CAPEX y OPEX",
  "Monthly expenditure": "Gasto mensual",
  "Spending by area": "Gasto por área",
  "Spending by project": "Gasto por proyecto",
  "Accounts payable": "Cuentas por pagar",
  "Overdue approvals": "Aprobaciones vencidas",
  "Budget available": "Presupuesto disponible",
  "Budget execution matrix": "Matriz de ejecución presupuestal",
  "Assigned versus committed, executed, paid, and available balances.": "Saldos asignados, comprometidos, ejecutados, pagados y disponibles.",
  "Report history": "Historial de reportes",
  "Previously generated management exports remain available.": "Las exportaciones gerenciales generadas permanecen disponibles.",
  "Export management CSV": "Exportar CSV gerencial",
  "Management report generated.": "Reporte gerencial generado.",
  "No area data available.": "No hay datos por área disponibles.",
  "No project data available.": "No hay datos por proyecto disponibles.",
  Unassigned: "Sin asignar",
  "Pending fiscal processing": "Procesamiento fiscal pendiente",
  "CXP processing queue": "Bandeja de procesamiento CXP",
  "Budget-committed requests waiting for fiscal validation and preliminary accounting.": "Solicitudes con compromiso presupuestal pendientes de validación fiscal y contabilización preliminar.",
  "Review fiscal data": "Revisar datos fiscales",
  "Process account payable": "Procesar cuenta por pagar",
  "Fiscal duplicate control": "Control de duplicidad fiscal",
  "The system blocks repeated RUC + document type + series + number combinations.": "El sistema bloquea combinaciones repetidas de RUC + tipo de comprobante + serie + número.",
  "Document type": "Tipo de comprobante",
  Series: "Serie",
  "Document number": "Número de comprobante",
  "Document date": "Fecha del comprobante",
  "Accounting date": "Fecha contable",
  "Fiscal period": "Periodo fiscal",
  "Subaccount": "Subcuenta",
  "Accounting comments": "Comentarios contables",
  "Validate and create CXP": "Validar y crear CXP",
  "Fiscal document validated and account payable created.": "Comprobante fiscal validado y cuenta por pagar creada.",
  "Awaiting payment confirmation": "Confirmación de pago pendiente",
  "Payment date": "Fecha programada de pago",
  "Bank file format": "Formato de archivo bancario",
  "Payment confirmation": "Confirmación de pago",
  "Record the actual bank operation number and payment date after the file is processed.": "Registra el número real de operación bancaria y la fecha de pago después de procesar el archivo.",
  "Confirm payment": "Confirmar pago",
  "Confirm bank payment": "Confirmar pago bancario",
  "Operation number": "Número de operación",
  "Actual payment date": "Fecha real de pago",
  "Payment operation confirmed.": "Operación de pago confirmada.",
  "Fiscal address": "Domicilio fiscal",
  "Legal representative": "Representante legal",
  "Contact name": "Nombre de contacto",
  "Supplier type": "Tipo de proveedor",
  "RUC file": "Ficha RUC",
  "Bank certificate": "Certificación bancaria",
  "Legal representative ID": "DNI del representante legal",
  "Required for homologation": "Obligatorio para homologación",
  "Active taxpayer": "Contribuyente activo",
  "Compliance approved": "Compliance aprobado",
  "Compliance comments": "Comentarios de compliance",
  "Homologation status": "Estado de homologación",
  "Homologation documents": "Documentos de homologación",
  "Void request": "Anular solicitud",
  "Fiscal document": "Comprobante fiscal",
  "Processed by": "Procesado por",
  "Confirmed by": "Confirmado por",
  "Use only when the role is Approver.": "Se usa solo cuando el rol es Aprobador.",
  "Supplier not found? Register it for homologation": "¿Proveedor no encontrado? Regístralo para homologación",
  "Approval SLA overdue": "SLA de aprobación vencido",
  OBSERVADO: "OBSERVADO",
  DEVUELTO: "DEVUELTO"
};

const productionSpanish = {
  "Accounts Payable": "Cuentas por pagar",
  "Review CXP balances, vouchers, payment batches, and settlement status independently from the request workflow.": "Revisa saldos CXP, comprobantes, lotes de pago y su liquidación de forma independiente al estado de la solicitud.",
  "Original amount": "Monto original",
  "Outstanding amount": "Monto pendiente",
  "Outstanding balance": "Saldo pendiente",
  "Payment batch": "Lote de pago",
  "Provision entry": "Asiento de provisión",
  "Payment entry": "Asiento de pago",
  "CXP history": "Historial CXP",
  "CXP status": "Estado CXP",
  "Eligible CXP": "CXP elegibles",
  "Due date": "Fecha de vencimiento",
  "Fiscal voucher": "Comprobante fiscal",
  "This settles Accounts Payable": "Esto liquida la cuenta por pagar",
  "Payment is not yet confirmed": "El pago aún no está confirmado",
  "Bank instruction generated": "Instrucción bancaria generada",
  "Bank batch": "Lote bancario",
  "Payment operation": "Operación de pago",
  "Confirmed amount": "Monto confirmado",
  "Confirm only after the bank has actually executed the instruction.": "Confirma solo después de que el banco haya ejecutado realmente la instrucción.",
  "Confirmation posts the payment journal, updates budget paid figures, and cannot be inferred from a downloaded TXT.": "La confirmación registra el asiento de pago y actualiza el presupuesto pagado; no se deduce de la descarga de un TXT.",
  "A request needs an active supplier bank account for the selected bank and currency before file generation.": "La solicitud necesita una cuenta bancaria activa del proveedor para el banco y moneda seleccionados antes de generar el archivo.",
  "No matching active account": "No existe una cuenta activa coincidente",
  "This supplier has no active bank account. Treasury cannot include it in a bank file until one is registered.": "Este proveedor no tiene una cuenta bancaria activa. Tesorería no puede incluirlo en un archivo hasta que se registre una.",
  "One bank file contains one bank and one currency. Only matching active accounts are selectable.": "Cada archivo bancario contiene un banco y una moneda. Solo se pueden seleccionar cuentas activas coincidentes.",
  "Every batch retains its checksum, adapter mode, items, and generation user.": "Cada lote conserva su checksum, modo de adaptador, elementos y usuario generador.",
  "Schedule eligible CXP, create bank instructions, confirm actual execution, and reconcile payments.": "Programa CXP elegibles, crea instrucciones bancarias, confirma la ejecución real y concilia los pagos.",
  "Reconciliation": "Conciliación",
  "Bank reference": "Referencia bancaria",
  "Statement amount": "Monto del estado bancario",
  "Match the confirmed payment to the bank statement before Accounting closure.": "Compara el pago confirmado con el estado bancario antes del cierre contable.",
  "Budget Control": "Control presupuestal",
  "Monitor and control assigned, committed, executed, paid, and available budget using the same dimensional ledger as workflow transactions.": "Controla el presupuesto asignado, comprometido, ejecutado, pagado y disponible usando el mismo registro dimensional del flujo.",
  "Manage allocations": "Gestionar asignaciones",
  "Dimensional budget": "Presupuesto dimensional",
  "Budget amount": "Monto presupuestal",
  "Budget attention required": "Atención presupuestal requerida",
  "Budget exceptions": "Excepciones presupuestales",
  "Period, Cost Center, expense classification, and project remain visible together.": "El período, centro de costos, clasificación del gasto y proyecto permanecen visibles en conjunto.",
  "Reservation, execution, payment, and release are independent and traceable.": "La reserva, ejecución, pago y liberación son independientes y trazables.",
  "One or more dimensions have low availability or over-execution.": "Una o más dimensiones tienen baja disponibilidad o sobreejecución.",
  "Insufficient-budget branches require an explicit decision and remain auditable.": "Las excepciones por presupuesto insuficiente requieren una decisión explícita y quedan auditadas.",
  "Commit budget": "Comprometer presupuesto",
  "Audit Viewer": "Visor de auditoría",
  "Read-only, insert-only history of workflow decisions, financial operations, overrides, and blocked controls.": "Historial de solo lectura y solo inserción de decisiones, operaciones financieras, excepciones y controles bloqueados.",
  "Financial control records": "Registros de control financiero",
  "Immutable audit": "Auditoría inmutable",
  "Application audit records are append-only.": "Los registros de auditoría de la aplicación solo permiten nuevas inserciones.",
  "Timestamp": "Fecha y hora",
  "IP address": "Dirección IP",
  "Entity": "Entidad",
  "Record ID": "ID del registro",
  "Request ID": "ID de la solicitud",
  "Block reason": "Motivo del bloqueo",
  "Recorded values": "Valores registrados",
  "No audit events available.": "No hay eventos de auditoría disponibles.",
  "Configuration sections": "Secciones de configuración",
  "Projects": "Proyectos",
  "Maintain active project dimensions used by requests, budgets, and management reporting.": "Mantiene proyectos activos usados por solicitudes, presupuestos y reportes gerenciales.",
  "Approval Rules": "Reglas de aprobación",
  "Configure approval sequence, role, amount range, area, and SLA without hard-coding workflow decisions in the UI.": "Configura secuencia, rol, rango de monto, área y SLA sin fijar decisiones del flujo en la interfaz.",
  "Budget Rules": "Reglas presupuestales",
  "Select active or transitional control and the explicit insufficient-budget exception strategy by dimension.": "Selecciona control activo o transitorio y la estrategia explícita para presupuesto insuficiente por dimensión.",
  "Budget Allocations": "Asignaciones presupuestales",
  "Maintain assigned budget by period, Cost Center, expense classification, and project.": "Mantiene el presupuesto asignado por período, centro de costos, clasificación del gasto y proyecto.",
  "Document Rules": "Reglas documentales",
  "Configure the evidence required by request type and expense nature. Requirements use kind, minCount, and labelKey.": "Configura la evidencia requerida por tipo de solicitud y naturaleza del gasto. Los requisitos usan kind, minCount y labelKey.",
  "Accounting Mappings": "Mapeos contables",
  "Configure expense, asset, non-deductible, CXP, bank, IGV, advance, and return accounts used by posting services.": "Configura las cuentas de gasto, activo, no deducible, CXP, banco, IGV, adelanto y devolución usadas en la contabilización.",
  "Bank Formats": "Formatos bancarios",
  "Record bank-adapter mode and specification version. Demo formats remain clearly marked as not certified.": "Registra el modo del adaptador y la versión de especificación. Los formatos demo se identifican como no certificados.",
  "Amount from": "Monto desde",
  "Amount to": "Monto hasta",
  "Sequence": "Secuencia",
  "SLA hours": "Horas SLA",
  "Required": "Obligatorio",
  "Mode": "Modo",
  "Exception strategy": "Estrategia de excepción",
  "Effective from": "Vigente desde",
  "Effective to": "Vigente hasta",
  "Period / year": "Periodo / año",
  "Assigned amount": "Monto asignado",
  "Requirements JSON": "Requisitos JSON",
  "Requirements": "Requisitos",
  "Purpose": "Finalidad",
  "Specification version": "Versión de especificación",
  "Certified": "Certificado",
  "Notes": "Notas",
  "Requirements must be a JSON array.": "Los requisitos deben ser un arreglo JSON.",
  "New period": "Nuevo período",
  "New accounting period": "Nuevo período contable",
  "Create an open period before financial activity begins.": "Crea un período abierto antes de iniciar la actividad financiera.",
  "Opening comments": "Comentarios de apertura",
  "Accounting period must be open.": "El período contable debe estar abierto.",
  "No open accounting period is configured.": "No hay un período contable abierto configurado.",
  "A minimum of {count} {document} file(s) is required.": "Se requiere un mínimo de {count} archivo(s) de {document}.",
  "Open, close, and reopen fiscal periods through explicit audited controls.": "Abre, cierra y reabre períodos fiscales mediante controles explícitos y auditados.",
  "Process fiscal documents, post balanced journals, reconcile the month, and retain export history.": "Procesa comprobantes fiscales, registra asientos balanceados, concilia el mes y conserva el historial de exportaciones.",
  "Export is blocked until the reconciliation difference is zero and journals balance.": "La exportación se bloquea hasta que la diferencia sea cero y los asientos estén balanceados.",
  "The posting account is still validated against the configured mapping.": "La cuenta contable también se valida contra el mapeo configurado.",
  "SIRE RCE Preparation": "Preparación SIRE RCE",
  "Validate eligible purchase-register rows and create a review CSV. No direct SUNAT submission is performed.": "Valida filas elegibles del registro de compras y crea un CSV de revisión. No se realiza envío directo a SUNAT.",
  "Run preview and resolve errors before export.": "Ejecuta la vista previa y resuelve los errores antes de exportar.",
  "Documents and fiscal validation": "Documentos y validación fiscal",
  "Physical files remain separate from extracted XML metadata.": "Los archivos físicos permanecen separados de los metadatos extraídos del XML.",
  "No XML validation result is stored.": "No existe un resultado de validación XML almacenado.",
  "Required evidence complete": "Evidencia obligatoria completa",
  "Required evidence incomplete": "Evidencia obligatoria incompleta",
  "Required documents are incomplete.": "Los documentos obligatorios están incompletos.",
  "No additional configured evidence for this classification.": "No hay evidencia adicional configurada para esta clasificación.",
  "Validated Cost Center and account dimensions with exact totals.": "Dimensiones de centro de costos y cuenta validadas con totales exactos.",
  "Budget, purchase order, CXP, journals, bank batches, payment, and reconciliation remain independently traceable.": "Presupuesto, orden de compra, CXP, asientos, lotes bancarios, pago y conciliación mantienen trazabilidad independiente.",
  "The backend revalidates permission, period, status, documents, supplier, fiscal, and budget controls.": "El backend vuelve a validar permisos, período, estado, documentos, proveedor y controles fiscales y presupuestales.",
  "Starts the configured approval route.": "Inicia la ruta de aprobación configurada.",
  "Electronic sign-offs, SLA dates, and workflow decisions.": "Conformidades electrónicas, fechas SLA y decisiones del flujo.",
  "Annul request": "Anular solicitud",
  "Observe": "Observar",
  "Return": "Devolver",
  "Rendition": "Rendición",
  "Amount advanced": "Monto entregado",
  "Amount rendered": "Monto rendido",
  "Amount returned": "Monto devuelto",
  "Rendition evidence": "Evidencia de rendición",
  "Rendered plus returned amounts must equal the advance.": "El monto rendido más el devuelto debe ser igual al adelanto.",
  "The advance remains in the configured transit account until Accounting validates actual evidence.": "El adelanto permanece en la cuenta transitoria configurada hasta que Contabilidad valide la evidencia real.",
  "Validate rendition": "Validar rendición",
  "Validated": "Validado",
  "Submitted": "Enviado",
  "Line": "Línea",
  "No project": "Sin proyecto",
  "Date from": "Fecha desde",
  "Date to": "Fecha hasta",
  "Mark all read": "Marcar todo como leído",
  "All": "Todos",
  "Delete": "Eliminar",
  requests: "solicitudes",
  ENVIADO: "ENVIADO",
  CERRADO: "CERRADO",
  VALIDATED: "VALIDADO",
  PENDING: "PENDIENTE",
  BLOCKED: "BLOQUEADO",
  COMPLETED: "COMPLETADO",
  GENERATED: "GENERADO",
  PARTIALLY_CONFIRMED: "CONFIRMADO PARCIALMENTE",
  CONFIRMED: "CONFIRMADO",
  NOT_REQUIRED: "NO REQUERIDO",
  PAYMENT_FILE_CREATED: "ARCHIVO DE PAGO CREADO",
  CANCELLED: "CANCELADO",
  COMPLIANT: "CONFORME",
  NON_COMPLIANT: "NO CONFORME",
  HOMOLOGATED: "HOMOLOGADO",
  AVAILABLE: "DISPONIBLE",
  COMMITTED: "COMPROMETIDO",
  EXECUTED: "EJECUTADO",
  PAID: "PAGADO",
  SCHEDULED: "PROGRAMADO",
  DEMO: "DEMO",
  Budget: "Presupuesto",
  Management: "Gerencia",
  "Area Director": "Director de área",
  "Vice Rector": "Vicerrector",
  RECTORATE: "RECTORADO",
  GENERAL_MANAGEMENT: "GERENCIA GENERAL",
  "Advance to account": "Entrega a rendir",
  "Supported reimbursement": "Reembolso con sustento",
  "Unsupported reimbursement": "Reembolso sin sustento",
  "Quotation-based payment": "Pago con cotización",
  "Purchase of goods": "Compra de bienes",
  Services: "Servicios",
  "Professional fees": "Honorarios profesionales",
  Consulting: "Consultoría",
  Advertising: "Publicidad",
  Travel: "Viajes",
  Equipment: "Equipamiento",
  Technology: "Tecnología",
  Infrastructure: "Infraestructura",
  Laboratories: "Laboratorios",
  Library: "Biblioteca",
  Research: "Investigación",
  Maintenance: "Mantenimiento",
  "Petty cash": "Caja chica",
  "Reimbursement / liquidation": "Reembolso / liquidación"
};

const spanishDictionary = { ...spanish, ...additionalSpanish, ...productionSpanish };

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem("erp_language") || "en");

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  function changeLanguage(nextLanguage) {
    setLanguage(nextLanguage);
    localStorage.setItem("erp_language", nextLanguage);
    document.documentElement.lang = nextLanguage;
  }

  function toggleLanguage() {
    changeLanguage(language === "en" ? "es" : "en");
  }

  function t(text) {
    if (text === undefined || text === null) return "";
    if (language === "en") return text;
    return spanishDictionary[text] || text;
  }

  const value = useMemo(() => ({ language, setLanguage: changeLanguage, toggleLanguage, t }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
