export const ROLES = Object.freeze({
  ADMIN: "Admin",
  SOLICITOR: "Solicitor",
  APPROVER: "Approver",
  ACCOUNTING: "Accounting",
  TREASURY: "Treasury",
  BUDGET: "Budget",
  MANAGEMENT: "Management"
});

export const PERMISSIONS = Object.freeze({
  REQUEST_CREATE: "request:create",
  REQUEST_VIEW_ALL: "request:view-all",
  REQUEST_APPROVE: "request:approve",
  REQUEST_VOID: "request:void",
  SUPPLIER_PROPOSE: "supplier:propose",
  SUPPLIER_HOMOLOGATE: "supplier:homologate",
  SUPPLIER_BANK_VIEW: "supplier:bank-view",
  BUDGET_VIEW: "budget:view",
  BUDGET_MANAGE: "budget:manage",
  ACCOUNTING_PROCESS: "accounting:process",
  PERIOD_MANAGE: "period:manage",
  TREASURY_SCHEDULE: "treasury:schedule",
  TREASURY_FILE: "treasury:file",
  PAYMENT_CONFIRM: "payment:confirm",
  RECONCILE: "payment:reconcile",
  REPORT_VIEW: "report:view",
  AUDIT_VIEW: "audit:view",
  MASTER_DATA_MANAGE: "master-data:manage",
  USER_MANAGE: "user:manage"
});

export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.SOLICITOR]: [PERMISSIONS.REQUEST_CREATE, PERMISSIONS.SUPPLIER_PROPOSE],
  [ROLES.APPROVER]: [PERMISSIONS.REQUEST_VIEW_ALL, PERMISSIONS.REQUEST_APPROVE, PERMISSIONS.BUDGET_VIEW, PERMISSIONS.REPORT_VIEW],
  [ROLES.ACCOUNTING]: [
    PERMISSIONS.REQUEST_VIEW_ALL,
    PERMISSIONS.SUPPLIER_HOMOLOGATE,
    PERMISSIONS.SUPPLIER_BANK_VIEW,
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.ACCOUNTING_PROCESS,
    PERMISSIONS.PERIOD_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.MASTER_DATA_MANAGE,
    PERMISSIONS.AUDIT_VIEW
  ],
  [ROLES.TREASURY]: [
    PERMISSIONS.REQUEST_VIEW_ALL,
    PERMISSIONS.SUPPLIER_BANK_VIEW,
    PERMISSIONS.TREASURY_SCHEDULE,
    PERMISSIONS.TREASURY_FILE,
    PERMISSIONS.PAYMENT_CONFIRM,
    PERMISSIONS.RECONCILE,
    PERMISSIONS.REPORT_VIEW
  ],
  [ROLES.BUDGET]: [PERMISSIONS.REQUEST_VIEW_ALL, PERMISSIONS.BUDGET_VIEW, PERMISSIONS.BUDGET_MANAGE, PERMISSIONS.REPORT_VIEW],
  [ROLES.MANAGEMENT]: [PERMISSIONS.REQUEST_VIEW_ALL, PERMISSIONS.REQUEST_APPROVE, PERMISSIONS.BUDGET_VIEW, PERMISSIONS.REPORT_VIEW]
});

export const REQUEST_TYPE = Object.freeze({
  OPEX: "OPEX",
  CAPEX: "CAPEX",
  ENTREGA_RENDIR: "ENTREGA_RENDIR",
  REEMBOLSO_CON_SUSTENTO: "REEMBOLSO_CON_SUSTENTO",
  REEMBOLSO_SIN_SUSTENTO: "REEMBOLSO_SIN_SUSTENTO",
  PAGO_CON_COTIZACION: "PAGO_CON_COTIZACION"
});

export const REQUEST_TYPES = Object.freeze(Object.values(REQUEST_TYPE));

export const EXPENSE_NATURE = Object.freeze({
  GOODS: "GOODS",
  SERVICES: "SERVICES",
  PROFESSIONAL_FEES: "PROFESSIONAL_FEES",
  CONSULTING: "CONSULTING",
  ADVERTISING: "ADVERTISING",
  TRAVEL: "TRAVEL",
  EQUIPMENT: "EQUIPMENT",
  TECHNOLOGY: "TECHNOLOGY",
  INFRASTRUCTURE: "INFRASTRUCTURE",
  LABORATORIES: "LABORATORIES",
  LIBRARY: "LIBRARY",
  RESEARCH: "RESEARCH",
  MAINTENANCE: "MAINTENANCE",
  PETTY_CASH: "PETTY_CASH",
  REIMBURSEMENT_LIQUIDATION: "REIMBURSEMENT_LIQUIDATION"
});

export const EXPENSE_NATURES = Object.freeze(Object.values(EXPENSE_NATURE));
export const REQUEST_PRIORITIES = Object.freeze(["BAJA", "MEDIA", "ALTA"]);

export const APPROVAL_STAGES = Object.freeze({
  AREA_DIRECTOR: "AREA_DIRECTOR",
  VICE_RECTOR: "VICE_RECTOR",
  RECTORATE: "RECTORATE",
  GENERAL_MANAGEMENT: "GENERAL_MANAGEMENT",
  COMPLETE: "COMPLETE"
});

export const APPROVAL_ACTIONS = Object.freeze(["APPROVE", "OBSERVE", "RETURN", "REJECT"]);

export const REQUEST_STATUS = Object.freeze({
  DRAFT: "BORRADOR",
  VALIDATION: "EN_VALIDACION",
  SENT: "ENVIADO",
  PENDING_APPROVAL: "PENDIENTE_APROBACION",
  DIRECTOR_APPROVED: "APROBADO_DIRECTOR",
  VICE_RECTOR_APPROVED: "APROBADO_VICERRECTOR",
  BUDGET_COMMITTED: "COMPROMISO_PRESUPUESTAL",
  ACCOUNTED: "CONTABILIZADO",
  SCHEDULED: "PROGRAMADO",
  BANK_FILE_GENERATED: "TXT_GENERADO",
  PAID: "PAGADO",
  RECONCILED: "CONCILIADO",
  RENDITION_PENDING: "RENDICION_PENDIENTE",
  CLOSED: "CERRADO",
  OBSERVED: "OBSERVADO",
  RETURNED: "DEVUELTO",
  REJECTED: "RECHAZADO",
  VOIDED: "ANULADO"
});

export const CANONICAL_REQUEST_STATUSES = Object.freeze(Object.values(REQUEST_STATUS));

export const LEGACY_STATUS_MAP = Object.freeze({
  BORRADOR: REQUEST_STATUS.DRAFT,
  PENDIENTE_APROBACION: REQUEST_STATUS.PENDING_APPROVAL,
  APROBADO_DIRECTOR: REQUEST_STATUS.DIRECTOR_APPROVED,
  APROBADO_VICERRECTOR: REQUEST_STATUS.VICE_RECTOR_APPROVED,
  COMPROMISO_PRESUPUESTAL: REQUEST_STATUS.BUDGET_COMMITTED,
  PROCESADO_BANCO: REQUEST_STATUS.BANK_FILE_GENERATED,
  PAGADO: REQUEST_STATUS.PAID,
  LIQUIDADO_CERRADO: REQUEST_STATUS.CLOSED,
  RENDICION_PENDIENTE: REQUEST_STATUS.RENDITION_PENDING,
  ANULADO: REQUEST_STATUS.VOIDED
});

export const LEGACY_REQUEST_TYPE_MAP = Object.freeze({
  OPEX: REQUEST_TYPE.OPEX,
  CAPEX: REQUEST_TYPE.CAPEX,
  "Entrega a Rendir": REQUEST_TYPE.ENTREGA_RENDIR,
  "Reembolso con Sustento": REQUEST_TYPE.REEMBOLSO_CON_SUSTENTO,
  "Reembolso sin Sustento": REQUEST_TYPE.REEMBOLSO_SIN_SUSTENTO,
  "Pago con Cotizacion": REQUEST_TYPE.PAGO_CON_COTIZACION,
  "Pago con Cotización": REQUEST_TYPE.PAGO_CON_COTIZACION
});

export const LEGACY_EXPENSE_NATURE_MAP = Object.freeze({
  "Compra de Bienes": EXPENSE_NATURE.GOODS,
  "Contratacion de Servicios": EXPENSE_NATURE.SERVICES,
  "Contratación de Servicios": EXPENSE_NATURE.SERVICES,
  "Honorarios Profesionales": EXPENSE_NATURE.PROFESSIONAL_FEES,
  Publicidad: EXPENSE_NATURE.ADVERTISING,
  Viajes: EXPENSE_NATURE.TRAVEL,
  Equipamiento: EXPENSE_NATURE.EQUIPMENT,
  Tecnologia: EXPENSE_NATURE.TECHNOLOGY,
  "Tecnología": EXPENSE_NATURE.TECHNOLOGY,
  Infraestructura: EXPENSE_NATURE.INFRASTRUCTURE,
  Laboratorios: EXPENSE_NATURE.LABORATORIES,
  Biblioteca: EXPENSE_NATURE.LIBRARY,
  Investigacion: EXPENSE_NATURE.RESEARCH,
  "Investigación": EXPENSE_NATURE.RESEARCH,
  Mantenimiento: EXPENSE_NATURE.MAINTENANCE,
  "Caja Chica": EXPENSE_NATURE.PETTY_CASH,
  "Reembolso / Liquidacion": EXPENSE_NATURE.REIMBURSEMENT_LIQUIDATION,
  "Reembolso / Liquidación": EXPENSE_NATURE.REIMBURSEMENT_LIQUIDATION
});

export const MANDATORY_XML_TYPES = Object.freeze([
  REQUEST_TYPE.PAGO_CON_COTIZACION,
  REQUEST_TYPE.REEMBOLSO_CON_SUSTENTO
]);

export const DEFAULT_APPROVAL_SLA_HOURS = 24;
export const APPROVAL_SLA_HOURS = Object.freeze({
  [APPROVAL_STAGES.AREA_DIRECTOR]: DEFAULT_APPROVAL_SLA_HOURS,
  [APPROVAL_STAGES.VICE_RECTOR]: DEFAULT_APPROVAL_SLA_HOURS,
  [APPROVAL_STAGES.RECTORATE]: DEFAULT_APPROVAL_SLA_HOURS,
  [APPROVAL_STAGES.GENERAL_MANAGEMENT]: DEFAULT_APPROVAL_SLA_HOURS
});

export const CURRENCY = Object.freeze(["PEN", "USD"]);
export const BANKS = Object.freeze(["BCP", "BBVA", "INTERBANK", "SCOTIABANK"]);

export const BUDGET_MODES = Object.freeze(["TRANSITIONAL", "ACTIVE"]);
export const BUDGET_EXCEPTION_STRATEGIES = Object.freeze(["REJECT", "REQUEST_BUDGET_INCREASE", "EXTRAORDINARY_APPROVAL"]);
export const BUDGET_STATUS = Object.freeze({
  NO_BUDGET: "NO_BUDGET",
  AVAILABLE: "AVAILABLE",
  COMMITTED: "COMMITTED",
  EXECUTED: "EXECUTED",
  RELEASED: "RELEASED",
  CLOSED: "CLOSED"
});

export const AP_STATUS = Object.freeze({
  OPEN: "OPEN",
  SCHEDULED: "SCHEDULED",
  PAYMENT_FILE_CREATED: "PAYMENT_FILE_CREATED",
  PAID: "PAID",
  CANCELLED: "CANCELLED"
});

export const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: "VALIDATION_ERROR",
  MISSING_REQUIRED_DOCUMENT: "MISSING_REQUIRED_DOCUMENT",
  XML_AMOUNT_MISMATCH: "XML_AMOUNT_MISMATCH",
  XML_VALIDATION_FAILED: "XML_VALIDATION_FAILED",
  SUPPLIER_NOT_HOMOLOGATED: "SUPPLIER_NOT_HOMOLOGATED",
  DUPLICATE_SUPPLIER: "DUPLICATE_SUPPLIER",
  DUPLICATE_VOUCHER: "DUPLICATE_VOUCHER",
  INSUFFICIENT_BUDGET: "INSUFFICIENT_BUDGET",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  ACCOUNTING_PERIOD_CLOSED: "ACCOUNTING_PERIOD_CLOSED",
  ACCOUNTING_PERIOD_MISSING: "ACCOUNTING_PERIOD_MISSING",
  EXCHANGE_RATE_MISSING: "EXCHANGE_RATE_MISSING",
  BANK_DETAILS_MISSING: "BANK_DETAILS_MISSING",
  RENDITION_REQUIRED: "RENDITION_REQUIRED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTEGRATION_NOT_CONFIGURED: "INTEGRATION_NOT_CONFIGURED"
});

export const CLOSED_PERIOD_MESSAGE =
  "The accounting period is closed. Records or modifications are not permitted for this period.";
